version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app   # bind mount current folder to /app inside container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
