name: Flask Deployment

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Deploy in EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        USER_NAME: ${{ secrets.USER_NAME }}
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}

      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
          ls &&
          cd /mnt/data/GitHub_Actions/ &&
          ls &&
          git pull &&
          echo \"$SUDO_PASSWORD\" | sudo -S systemctl stop flaskapp &&
          echo \"$SUDO_PASSWORD\" | sudo -S systemctl daemon-reload &&
          echo \"$SUDO_PASSWORD\" | sudo -S systemctl start flaskapp
        "
